{"time":"2025-10-10T19:27:41.6882081+02:00","level":"INFO","msg":"stream: starting","core version":"0.22.2"}
{"time":"2025-10-10T19:27:42.7377543+02:00","level":"INFO","msg":"stream: created new stream","id":"u7uo4vw7"}
{"time":"2025-10-10T19:27:42.7377543+02:00","level":"INFO","msg":"handler: started","stream_id":"u7uo4vw7"}
{"time":"2025-10-10T19:27:42.7476761+02:00","level":"INFO","msg":"stream: started","id":"u7uo4vw7"}
{"time":"2025-10-10T19:27:42.7476761+02:00","level":"INFO","msg":"writer: started","stream_id":"u7uo4vw7"}
{"time":"2025-10-10T19:27:42.7476761+02:00","level":"INFO","msg":"sender: started","stream_id":"u7uo4vw7"}
{"time":"2025-10-10T19:42:13.8557112+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": net/http: request canceled (Client.Timeout exceeded while awaiting headers)"}
{"time":"2025-10-10T19:42:30.7851135+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 172.20.10.2:54553->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-10T19:42:56.8575462+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/j-chemirmir-glasgow-caledonian-university/huggingface/u7uo4vw7/file_stream\": read tcp 172.20.10.2:53748->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-10T19:43:05.3656764+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": context deadline exceeded"}
{"time":"2025-10-10T19:43:44.8294519+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": context deadline exceeded"}
{"time":"2025-10-10T19:44:24.7276275+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 172.20.10.2:58377->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-10T19:44:32.1276725+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/j-chemirmir-glasgow-caledonian-university/huggingface/u7uo4vw7/file_stream\": read tcp 172.20.10.2:55433->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-10T19:45:27.9569397+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}
{"time":"2025-10-10T19:45:40.427243+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/j-chemirmir-glasgow-caledonian-university/huggingface/u7uo4vw7/file_stream\": read tcp 172.20.10.2:53834->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-10T19:46:08.2478839+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/j-chemirmir-glasgow-caledonian-university/huggingface/u7uo4vw7/file_stream\": read tcp 172.20.10.2:65328->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-10T19:46:52.9345606+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/j-chemirmir-glasgow-caledonian-university/huggingface/u7uo4vw7/file_stream\": read tcp 172.20.10.2:62515->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-10T19:46:57.958131+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": context deadline exceeded"}
{"time":"2025-10-10T19:48:27.9601737+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": context deadline exceeded"}
{"time":"2025-10-10T19:49:38.7575054+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/j-chemirmir-glasgow-caledonian-university/huggingface/u7uo4vw7/file_stream\": read tcp 172.20.10.2:50757->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-10T19:49:49.9463094+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 172.20.10.2:58514->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-10T19:50:13.2475604+02:00","level":"INFO","msg":"flowcontrol: backed up, offloading to disk","recordNumber":111}
{"time":"2025-10-10T19:51:00.852127+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/j-chemirmir-glasgow-caledonian-university/huggingface/u7uo4vw7/file_stream\": read tcp 172.20.10.2:62751->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-10T19:51:10.0675869+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 172.20.10.2:63496->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-10T19:51:43.8563176+02:00","level":"WARN","msg":"sender: taking a long time","seconds":600.0003052,"work":"WorkRecord(*service_go_proto.Request_StopStatus); Control(local:true mailbox_slot:\"g9fdf5hl0761\" connection_id:\"1(127.0.0.1:54549)\")"}
{"time":"2025-10-10T19:52:19.9752331+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/j-chemirmir-glasgow-caledonian-university/huggingface/u7uo4vw7/file_stream\": read tcp 172.20.10.2:53256->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-10T19:52:29.1990864+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 172.20.10.2:51045->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-10T19:53:41.4628656+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/j-chemirmir-glasgow-caledonian-university/huggingface/u7uo4vw7/file_stream\": read tcp 172.20.10.2:57737->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-10T19:53:50.8765721+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 172.20.10.2:57949->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-10T19:55:00.9601673+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/j-chemirmir-glasgow-caledonian-university/huggingface/u7uo4vw7/file_stream\": read tcp 172.20.10.2:51965->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-10T19:55:20.8785278+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}
{"time":"2025-10-10T19:56:20.2596445+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/j-chemirmir-glasgow-caledonian-university/huggingface/u7uo4vw7/file_stream\": read tcp 172.20.10.2:65293->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-10T19:56:42.0635534+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 172.20.10.2:60821->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-10T19:57:41.1137065+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/j-chemirmir-glasgow-caledonian-university/huggingface/u7uo4vw7/file_stream\": read tcp 172.20.10.2:61597->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-10T19:58:01.214623+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 172.20.10.2:57134->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-10T19:59:00.2035473+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/j-chemirmir-glasgow-caledonian-university/huggingface/u7uo4vw7/file_stream\": read tcp 172.20.10.2:61548->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-10T19:59:25.3420392+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 172.20.10.2:60606->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-10T20:00:21.2004304+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/j-chemirmir-glasgow-caledonian-university/huggingface/u7uo4vw7/file_stream\": read tcp 172.20.10.2:52294->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-10T20:00:46.5274723+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 172.20.10.2:52178->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-10T20:01:42.0252833+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/j-chemirmir-glasgow-caledonian-university/huggingface/u7uo4vw7/file_stream\": read tcp 172.20.10.2:61721->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-10T20:01:43.8580015+02:00","level":"WARN","msg":"sender: taking a long time","seconds":1200.0025049,"work":"WorkRecord(*service_go_proto.Request_StopStatus); Control(local:true mailbox_slot:\"g9fdf5hl0761\" connection_id:\"1(127.0.0.1:54549)\")"}
{"time":"2025-10-10T20:02:16.5283495+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": context deadline exceeded"}
{"time":"2025-10-10T20:02:42.0288312+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/j-chemirmir-glasgow-caledonian-university/huggingface/u7uo4vw7/file_stream\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2025-10-10T20:03:16.5326451+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2025-10-10T20:03:42.0328757+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/j-chemirmir-glasgow-caledonian-university/huggingface/u7uo4vw7/file_stream\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2025-10-10T20:04:16.5402221+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2025-10-10T20:04:42.0368019+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/j-chemirmir-glasgow-caledonian-university/huggingface/u7uo4vw7/file_stream\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2025-10-10T20:05:16.5451608+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2025-10-10T20:05:16.5451608+02:00","level":"ERROR","msg":"sender: sendStopStatus: failed to get run stopped status: api: failed sending: POST https://api.wandb.ai/graphql giving up after 21 attempt(s): Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2025-10-10T20:05:16.5462874+02:00","level":"INFO","msg":"sender: succeeded after taking longer than expected","seconds":1412.6907908,"work":"WorkRecord(*service_go_proto.Request_StopStatus); Control(local:true mailbox_slot:\"g9fdf5hl0761\" connection_id:\"1(127.0.0.1:54549)\")"}
{"time":"2025-10-10T20:05:16.5479118+02:00","level":"INFO","msg":"flowcontrol: unblocked","totalOffloaded":61}
{"time":"2025-10-10T20:05:29.6288033+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2025-10-10T20:05:31.6502768+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2025-10-10T20:05:36.0610095+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2025-10-10T20:05:42.0397088+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/j-chemirmir-glasgow-caledonian-university/huggingface/u7uo4vw7/file_stream\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2025-10-10T20:05:44.3179243+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2025-10-10T20:06:03.0992696+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai: no such host"}
